### ISSUE TITLE
group_3_ass_1_2024

### ISSUE THREAD

**Issue by ZuleikaCalderon** [alexanderquispe/BiLab_Summer_Python#30]
Share information data we would like to study.

**Comment by Igor98h** [comment]
Igor
a. Database: INEI
b. Information: National survey of university and college graduates in 2014 
C. Interest: I would like to study information on the academic and complementary services offered by the university.

**Comment by Rvergaram** [comment]
It was a mistake

**Comment by Rvergaram** [comment]
It was a mistake
